apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: yosefshoval-dev
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_DATA_TOPIC: data
  KAFKA_IMAGE_TOPIC: images
  KAFKA_CONSUMER_GROUP: storage-worker-group
  MONGO_HOST: mongodb
  MONGO_PORT: "27017"
  MONGO_URI: mongodb://mongodb:27017
  MONGO_URI_SCANALYTICS_DB: mongodb://mongodb:27017/scanalytics_db
  MONGO_DB_NAME: metadata_db
  GRIDFS_DB_NAME: files_db
  MONGO_METADATA_DB: metadata_db
  ELASTICSEARCH_URL: http://elasticsearch:9200
  ES_HOST: http://elasticsearch:9200
  ES_INDEX: receipt_items
  VITE_AUTH_API_URL: http://backend:3000/api
  VITE_INGESTION_API_URL: http://api-gateway:8000
  VITE_INSIGHTS_API_URL: http://insights-dashboard:8001
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: yosefshoval-dev
type: Opaque
stringData:
  LLAMA_CLOUD_API_KEY: "llx-EMgQCwxcTzzdVoJ0b65Fg0zX4jlDhR0zgz9YbhPk3FykeqdM"