apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: yosefshoval-dev
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kafka-ui
  namespace: yosefshoval-dev
spec:
  to:
    kind: Service
    name: kafka-ui
  port:
    targetPort: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kibana
  namespace: yosefshoval-dev
spec:
  to:
    kind: Service
    name: kibana
  port:
    targetPort: http
